POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email":"maazi@gmail.com",
  "password":"123456789"
}
### get all users
GET http://localhost:3000/auth
Content-Type: application/json


### get user by id
GET http://localhost:3000/auth/4
Content-Type: application/json

### update user
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
  "email":"alimaazali6@gmail.com"
}

### delete user
DELETE http://localhost:3000/auth/5
Content-Type: application/json
